name: 'Example'
url: 'https://example.com'

basic:
  username: 
  password: 

oauth2:
  client_id:
  client_secret:
  authorize_url: 'https://example.com/login/oauth/authorize'
  token_url: 'https://example.com/login/oauth/access_token'
  scope:
