name: 'Github'
url: 'https://api.github.com'

oauth2:
  authorize_url: 'https://github.com/login/oauth/authorize'
  token_url: 'https://github.com/login/oauth/access_token'
  scope: 'repo,gist'

# Add these keys to your config/secrets.yml (https://github.com/settings/applications)
# github_client_id: <key-found-in-github-admin>
# github_client_secret: <key-found-in-github-admin>